language: r
cache: packages

addons:
  apt:
    packages:
      - libv8-dev
      - valgrind

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  # install tmap dependencies
  - sudo apt-get install --yes libprotobuf-dev protobuf-compiler libv8-3.14-dev
  # install tmap dependencies; for 16.04 libjq-dev this ppa is needed:
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libjq-dev
  # units/udunits2 dependency:
  - sudo apt-get install --yes libudunits2-dev
  # sf dependencies:
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev

sudo: required

dist: trusty

warnings_are_errors: true

r_github_packages:
  - mtennekes/tmaptools

r_packages:
  - sp
  - rgdal
  - rgeos
  - roxygen2
  - rmarkdown
