language: r

r:
  - release
  - devel

sudo: required
dist: trusty

cache: 
  - packages
  - ccache

addons:
  postgresql: "9.6"
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libudunits2-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libv8-3.14-dev
      - libjq-dev
      - libjson-c-dev
      - libcairo2-dev
      - postgresql-server-dev-9.6 # required for postgis installation

before_install:
  # install postgis from source (required for lwgeom installation):
  - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
  - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)
  # create postgis databases:
  - sudo service postgresql restart
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
  - createdb empty
  - psql -d empty -c "CREATE EXTENSION postgis;"
  - R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
script: R -q -e 'tic::script()'

r_github_packages:
  - mtennekes/tmaptools

before_deploy: R -q -e 'tic::before_deploy()'
deploy:
   provider: script
   script: R -q -e 'tic::deploy()'
   on:
     branch: develop
     condition:
       - $TRAVIS_PULL_REQUEST = false
       - $TRAVIS_EVENT_TYPE != cron
       - $TRAVIS_R_VERSION_STRING = release

after_success: 
  - R -q -e 'tic::after_success()'
  - R -q -e 'covr::codecov(quiet = FALSE)'
